disabling WAL breaks following test cases: --- FAIL: TestClient_BackupRestore (0.10s) --- FAIL: TestClient_BackupInverseView (0.07s) --- FAIL: TestFragment_WriteTo_ReadFrom (0.05s) --- FAIL: TestHandler_Fragment_BackupRestore (0.09s) --- FAIL: TestMain_FrameRestore (0.07s)